require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Flipper 설정 (Flipper를 완전히 비활성화)
flipper_config = FlipperConfiguration.disabled

# 사용하려는 프레임워크 설정
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'whoAmIToday' do
  config = use_native_modules!

  # 필요한 Firebase 및 Google Utilities 추가
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

  # react-native-fetch-blob 경로 지정
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  # 기본 플래그 가져오기
  flags = get_default_flags()

  # React Native 설정
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,  # Hermes 사용 여부 설정 (false로 설정)
    :fabric_enabled => flags[:fabric_enabled],  # Fabric 활성화 여부
    :flipper_configuration => flipper_config,  # Flipper 비활성화
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # 테스트 타겟 설정
  target 'whoAmITodayTests' do
    inherit! :complete
    # 테스트용 Pods 추가
  end

  # post_install 설정
  post_install do |installer|
    # React Native 관련 post-install 작업
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false  # Mac Catalyst 빌드를 위한 설정 (필요한 경우 true로 설정)
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end