default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Pod install 실행
    cocoapods

    # 자동으로 build number 증가
    increment_build_number(
      build_number: latest_testflight_build_number + 1
    )
    
    # 앱 빌드
    build_ios_app(
      scheme: "WhoAmIToday"
    )
    
    # TestFlight에 업로드
    upload_to_testflight
  end
end